CREATE TABLE PAIS (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL
);

CREATE TABLE ESCUELA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_PAIS_ID INTEGER NOT NULL
);

CREATE TABLE CURSO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO INTEGER NOT NULL,
    FK_ESCUELA_ID INTEGER NULL
);

CREATE TABLE SESION (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    TOTAL INTEGER NOT NULL,
    OBJETIVOS INTEGER NOT NULL,
    FK_CURSO_ID INTEGER NOT NULL
);

CREATE TABLE ETAPA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO INTEGER NOT NULL,
    FK_CURSO_ID INTEGER NOT NULL
);

CREATE TABLE RETO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_ETAPA_ID INTEGER NOT NULL
);

CREATE TABLE OBJETIVO_CODE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FK_RETO_ID INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL
);

CREATE TABLE DOCENTE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL 
);

CREATE TABLE SECCION (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    FK_CURSO_ID INTEGER NOT NULL,
    FK_DOCENTE_ID INTEGER NULL
);

CREATE TABLE ENTRENADOR (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_SECCION_ID INTEGER NOT NULL
);

CREATE TABLE REPRESENTANTE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL 
);

CREATE TABLE ALUMNO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DNI VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_SECCION_ID INTEGER NOT NULL,
    FK_REPRESENTANTE_ID INTEGER NULL
);

CREATE TABLE EQUIPO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    FK_ALUMNO_0_ID INTEGER NOT NULL,
    FK_ALUMNO_1_ID INTEGER NOT NULL
);

CREATE TABLE PROYECTO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL
);

CREATE TABLE RUBRICA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_PROYECTO_ID INTEGER NOT NULL
);

CREATE TABLE OBJETIVO_RUBRICA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    VALOR INTEGER NOT NULL,
    SESION_TARGET INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL,
    FK_RUBRICA_ID INTEGER NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);

CREATE TABLE AVANCE_RUBRICA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AVANCE VARCHAR(255) NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);

CREATE TABLE AVANCE_CODE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OBJETIVOS INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);

CREATE TABLE PREGUNTA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OBJETIVOS INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL
);

CREATE TABLE AVANCE_PREGUNTA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OBJETIVOS INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    FK_PREGUNTA_ID INTEGER NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);

CREATE TABLE VIDEO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NULL,
    PREGUNTA VARCHAR(255) NULL,
    OBJETIVOS INTEGER NOT NULL, 
    TOTAL INTEGER NOT NULL
);

CREATE TABLE OBJETIVO_VIDEO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FK_VIDEO_ID INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL
);

CREATE TABLE AVANCE_VIDEO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OBJETIVOS INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    RESPUESTA VARCHAR(255) NULL,
    FK_VIDEO_ID INTEGER NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);