CREATE TABLE PAIS (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL
);

CREATE TABLE ESCUELA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_PAIS_ID INTEGER NOT NULL
);

CREATE TABLE CURSO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO INTEGER NOT NULL,
    FK_ESCUELA_ID INTEGER NULL
);

CREATE TABLE SESION (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO INTEGER NOT NULL,
    FECHA DATE NOT NULL,
    TOTAL INTEGER NOT NULL,
    OBJETIVOS INTEGER NOT NULL,
    FK_CURSO_ID INTEGER NOT NULL
);

CREATE TABLE ETAPA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO INTEGER NOT NULL,
    FK_CURSO_ID INTEGER NOT NULL
);

CREATE TABLE RETO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_ETAPA_ID INTEGER NOT NULL
);

CREATE TABLE OBJETIVO_CODE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FK_RETO_ID INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL
);

CREATE TABLE DOCENTE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL 
);

CREATE TABLE SECCION (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    FK_CURSO_ID INTEGER NOT NULL,
    FK_DOCENTE_ID INTEGER NULL
);

CREATE TABLE ENTRENADOR (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_SECCION_ID INTEGER NOT NULL
);

CREATE TABLE REPRESENTANTE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL 
);

CREATE TABLE ALUMNO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DNI VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_SECCION_ID INTEGER NOT NULL,
    FK_REPRESENTANTE_ID INTEGER NULL
);

CREATE TABLE EQUIPO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    FK_ALUMNO_0_ID INTEGER NOT NULL,
    FK_ALUMNO_1_ID INTEGER NOT NULL
);

CREATE TABLE PROYECTO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL
);

CREATE TABLE RUBRICA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FK_PROYECTO_ID INTEGER NOT NULL
);

CREATE TABLE OBJETIVO_RUBRICA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    VALOR INTEGER NOT NULL,
    SESION_TARGET INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL,
    FK_RUBRICA_ID INTEGER NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);

CREATE TABLE AVANCE_RUBRICA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AVANCE VARCHAR(255) NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);

CREATE TABLE AVANCE_CODE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OBJETIVOS INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);

CREATE TABLE PREGUNTA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OBJETIVOS INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL
);

CREATE TABLE AVANCE_PREGUNTA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OBJETIVOS INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    FK_PREGUNTA_ID INTEGER NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);

CREATE TABLE VIDEO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NULL,
    PREGUNTA VARCHAR(255) NULL,
    OBJETIVOS INTEGER NOT NULL, 
    TOTAL INTEGER NOT NULL
);

CREATE TABLE OBJETIVO_VIDEO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FK_VIDEO_ID INTEGER NOT NULL,
    FK_SESION_ID INTEGER NOT NULL
);

CREATE TABLE AVANCE_VIDEO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OBJETIVOS INTEGER NOT NULL,
    TOTAL INTEGER NOT NULL,
    RESPUESTA VARCHAR(255) NULL,
    FK_VIDEO_ID INTEGER NOT NULL,
    FK_ALUMNO_ID INTEGER NOT NULL
);

-- ######################################################################################
-- ######################################################################################
-- ######################################################################################

ALTER TABLE ESCUELA ADD CONSTRAINT FK_PAIS_ID FOREIGN KEY(FK_PAIS_ID) REFERENCES PAIS(ID);

ALTER TABLE CURSO ADD CONSTRAINT FK_ESCUELA_ID FOREIGN KEY(FK_ESCUELA_ID) REFERENCES ESCUELA(ID);

ALTER TABLE ETAPA ADD CONSTRAINT FK_CURSO_ID_1 FOREIGN KEY(FK_CURSO_ID) REFERENCES CURSO(ID);

ALTER TABLE RETO ADD CONSTRAINT FK_ETAPA_ID FOREIGN KEY(FK_ETAPA_ID) REFERENCES ETAPA(ID);

ALTER TABLE OBJETIVO_CODE ADD CONSTRAINT FK_RETO_ID FOREIGN KEY(FK_RETO_ID) REFERENCES RETO(ID);
ALTER TABLE OBJETIVO_CODE ADD CONSTRAINT FK_SESION_ID FOREIGN KEY(FK_SESION_ID) REFERENCES SESION(ID);

ALTER TABLE SECCION ADD CONSTRAINT FK_CURSO_ID_2 FOREIGN KEY(FK_CURSO_ID) REFERENCES CURSO(ID);
ALTER TABLE SECCION ADD CONSTRAINT FK_DOCENTE_ID FOREIGN KEY(FK_DOCENTE_ID) REFERENCES DOCENTE(ID);

ALTER TABLE ENTRENADOR ADD CONSTRAINT FK_SECCION_ID FOREIGN KEY(FK_SECCION_ID) REFERENCES SECCION(ID);

ALTER TABLE EQUIPO ADD CONSTRAINT FK_ALUMNO_0_ID FOREIGN KEY(FK_ALUMNO_0_ID) REFERENCES ALUMNO(ID);
ALTER TABLE EQUIPO ADD CONSTRAINT FK_ALUMNO_1_ID FOREIGN KEY(FK_ALUMNO_1_ID) REFERENCES ALUMNO(ID);

ALTER TABLE RUBRICA ADD CONSTRAINT FK_PROYECTO_ID FOREIGN KEY(FK_PROYECTO_ID) REFERENCES PROYECTO(ID);

ALTER TABLE OBJETIVO_RUBRICA ADD CONSTRAINT FK_SESION_ID_1 FOREIGN KEY(FK_SESION_ID) REFERENCES SESION(ID);
ALTER TABLE OBJETIVO_RUBRICA ADD CONSTRAINT FK_RUBRICA_ID FOREIGN KEY(FK_RUBRICA_ID) REFERENCES RUBRICA(ID);
ALTER TABLE OBJETIVO_RUBRICA ADD CONSTRAINT FK_ALUMNO_ID_4 FOREIGN KEY(FK_ALUMNO_ID) REFERENCES ALUMNO(ID);

ALTER TABLE AVANCE_RUBRICA ADD CONSTRAINT FK_ALUMNO_ID FOREIGN KEY(FK_ALUMNO_ID) REFERENCES ALUMNO(ID);

ALTER TABLE AVANCE_CODE ADD CONSTRAINT FK_SESION_ID_2 FOREIGN KEY(FK_SESION_ID) REFERENCES SESION(ID);
ALTER TABLE AVANCE_CODE ADD CONSTRAINT FK_ALUMNO_ID_1 FOREIGN KEY(FK_ALUMNO_ID) REFERENCES ALUMNO(ID);

ALTER TABLE OBJETIVO_VIDEO ADD CONSTRAINT FK_VIDEO_ID FOREIGN KEY(FK_VIDEO_ID) REFERENCES VIDEO(ID);
ALTER TABLE OBJETIVO_VIDEO ADD CONSTRAINT FK_SESION_ID_3 FOREIGN KEY(FK_SESION_ID) REFERENCES SESION(ID);

ALTER TABLE AVANCE_VIDEO ADD CONSTRAINT FK_VIDEO_ID_1 FOREIGN KEY(FK_VIDEO_ID) REFERENCES VIDEO(ID);
ALTER TABLE AVANCE_VIDEO ADD CONSTRAINT FK_ALUMNO_ID_2 FOREIGN KEY(FK_ALUMNO_ID) REFERENCES ALUMNO(ID);

ALTER TABLE PREGUNTA ADD CONSTRAINT FK_SESION_ID_4 FOREIGN KEY(FK_SESION_ID) REFERENCES SESION(ID);

ALTER TABLE AVANCE_PREGUNTA ADD CONSTRAINT FK_PREGUNTA_ID_1 FOREIGN KEY(FK_PREGUNTA_ID) REFERENCES PREGUNTA(ID);
ALTER TABLE AVANCE_PREGUNTA ADD CONSTRAINT FK_ALUMNO_ID_3 FOREIGN KEY(FK_ALUMNO_ID) REFERENCES ALUMNO(ID);